
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFEREN = 11;
  public static final int CARACTERES = 14;
  public static final int LLAV_C = 5;
  public static final int LLAV_A = 4;
  public static final int OPERA = 18;
  public static final int DOSP = 6;
  public static final int ID = 13;
  public static final int COMPLE = 12;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int CONJ = 16;
  public static final int PARENTESIS_C = 3;
  public static final int error = 1;
  public static final int PARENTESIS_A = 2;
  public static final int EVALUAR = 17;
  public static final int ENTERO = 15;
  public static final int INTER = 10;
  public static final int PCOMA = 8;
  public static final int FLECH = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "LLAV_A",
  "LLAV_C",
  "DOSP",
  "FLECH",
  "PCOMA",
  "COMA",
  "INTER",
  "DIFEREN",
  "COMPLE",
  "ID",
  "CARACTERES",
  "ENTERO",
  "CONJ",
  "EVALUAR",
  "OPERA"
  };
}

